apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-management
  labels:
    app: employee-management

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: employee-management

  template:
    metadata:
      labels:
        app: employee-management

    spec:
      containers:
        - name: employee-management

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://{{ .Values.db.host }}:{{ .Values.db.port }}/employee_management_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

            - name: SPRING_DATASOURCE_USERNAME
              value: "sakthi"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "sakthi123"

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi