apiVersion: v1
kind: Service
metadata:
  name: employee-management
  labels:
    app: employee-management

spec:
  type: {{ .Values.service.type }}

  selector:
    app: employee-management

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
